name: X Poster

on:
  # Run once daily, ~5 minutes after fetcher (allows time for Notion write)
  schedule:
    - cron: "10 8 * 3-10 *"     # 08:10 UTC ≈ 10:10 Paris during CEST (Mar–Oct)
    - cron: "10 9 * 11,12,1,2 *" # 09:10 UTC ≈ 10:10 Paris during CET (Nov–Feb)
  workflow_run:
    workflows: ["AI Content Fetcher"]  # run right after fetcher
    types: [completed]

concurrency:
  group: x-poster
  cancel-in-progress: true

jobs:
  post:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'schedule'
      || (github.event_name == 'workflow_run'
          && github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pre-check Notion for ready posts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: python check_ready_to_post.py || { echo "No Scheduled rows ready. Skipping."; exit 0; }

      - name: Run Poster
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        run: python main.py
